export const artistChips = [
  {
    id: 'painters',
    name: 'Painters',
    description: 'List of some famous painters',
    chips: [
      'Alberto Giacometti',
      'Amedeo Modigliani',
      'Anselm Kiefer',
      'Antoni Gaudí',
      'Auguste Rodin',
      'Camille Corot',
      'Camille Pissarro',
      'Caravaggio',
      'Claude Monet',
      'Dante Gabriel Rossetti',
      'David Hockney',
      'Diego Velázquez',
      'Edgar Degas',
      'Edvard Munch',
      'Edward Burne-Jones',
      'Edward Hopper',
      'Édgar Degas',
      'Édouard Manet',
      'Émile Bernard',
      'El Greco',
      'Emil Nolde',
      'Francis Bacon',
      'Francisco Goya',
      'Frederic Leighton',
      'Frida Kahlo',
      'Georges Braque',
      'Georges Rouault',
      'Georges Seurat',
      'Giotto di Bondone',
      'Gustave Caillebotte',
      'Gustave Courbet',
      'Gustave Klimt',
      'Hans Holbein the Younger',
      'Henri Matisse',
      'Henri Rousseau',
      'Henri de Toulouse-Lautrec',
      'James McNeill Whistler',
      'Jean-Auguste-Dominique Ingres',
      'Jean-Baptiste-Siméon Chardin',
      'Jean-Francois Millet',
      'Joan Miró',
      'John Constable',
      'John Everett Millais',
      'John Singer Sargent',
      'John William Waterhouse',
      'Joseph Beuys',
      'Katsushika Hokusai',
      'Kazimir Malevich',
      'Leonardo da Vinci',
      'Marc Chagall',
      'Mark Rothko',
      'Michelangelo',
      'Odilon Redon',
      'Paul Cézanne',
      'Paul Gauguin',
      'Peter Claesz',
      'Peter Paul Rubens',
      'Pieter Bruegel the Elder',
      'Pieter Claesz',
      'Pablo Picasso',
      'Rembrandt',
      'René Magritte',
      'Rogier van der Weyden',
      'Roy Lichtenstein',
      'Rubens, Peter Paul',
      'Raphael',
      'Salvador Dalí',
      'Sandro Botticelli',
      'Seurat, Georges-Pierre',
      'Thomas Gainsborough',
      'Titian',
      'Velázquez, Diego',
      'Victor Vasarely',
      'Vincent van Gogh',
      'Willem de Kooning',
      'William Blake',
      'William Bouguereau',
      'William Holman Hunt',
      'William Morris',
      'William Turner',
    ],
  },

  {
    id: 'photographers',
    name: 'Photographers',
    description: 'List of photographers',
    chips: [
      'Adams, Ansel',
      'Abbott, Berenice',
      'Araki, Nobuyoshi',
      'Arbus, Diane',
      'Atget, Eugene',
      'Avedon, Richard',
      'Bailey, David',
      'Baldessari, John',
      'Basilico, Gabriele',
      'Bellmer, Hans',
      'Burtynsky, Edward',
      'Callahan, Harry',
      'Capa, Robert',
      'Cartier-Bresson, Henri',
      'Coburn, Alvin Langdon',
      'Calle, Sophie',
      'Clark, Larry',
      'Crewdson, Gregory',
      'Cunningham, Imogen',
      'Dater, Judy',
      'Davidson, Bruce',
      'Demand, Thomas',
      'Dijkstra, Rineke',
      'Doisneau, Robert',
      'Eggleston, William',
      'Erwitt, Elliott',
      'Evans, Walker',
      'Fink, Larry',
      'Frank, Robert',
      'Friedlander, Lee',
      'Gilden, Bruce',
      'Goldblatt, David',
      'Goldin, Nan',
      'Greenfield, Lauren',
      'Güler, Ara',
      'Gursky, Andreas',
      'Haas, Ernst',
      'Hine, Lewis',
      'Hiroshi Sugimoto',
      'Horn, Roni',
      'Izu, Kenro',
      'Karsh, Yousuf',
      'Killip, Chris',
      'Kenna, Michael',
      'Klein, William',
      'Lachapelle, David',
      'Lange, Dorothea',
      'Lee, Nikki',
      'Leibovitz, Annie',
      'Lindbergh, Peter',
      'Mann, Sally',
      'Mark, Mary Ellen',
      'Meatyard, Ralph Eugene',
      'Michals, Duane',
      'Miller, Lee',
      'Moholy-Nagy, Laszlo',
      'Moriyama, Daido',
      'Modotti, Tina',
      'Mapplethorpe, Robert',
      'Muybridge, Eadweard',
      'Newton, Helmut',
      'Neshat, Shirin',
      'Nachtwey, James',
      'Parks, Gordon',
      'Parke, Trent',
      'Parr, Martin',
      'Penn, Irving',
      'Ray, Man',
      'Ritts, Herb',
      'Sherman, Cindy',
      'Smith, W. Eugene',
      'Soth, Alec',
      'Steichen, Edward',
      'Strand, Paul',
      'Steve McCurry',
      'Sugimoto, Hiroshi',
      'Tillmans, Wolfgang',
      'Tina Modotti',
      'Webb, Alex',
      'Weegee',
      'Weston, Edward',
      'White, Minor',
      'William Eggleston',
      'William Klein',
      'Woodman, Francesca',
      'Witkin, Joel-Peter',
    ],
  },
  {
    id: 'mediums',
    name: 'Mediums',
    description: 'List of mediums',
    chips: [
      'Abstract art',
      'Acrylic',
      'Airbrush',
      'Art deco',
      'Art nouveau',
      'Assemblage',
      'Basket weaving',
      'Block printing',
      'Calligraphy',
      'Ceramics',
      'Charcoal',
      'Chalk',
      'Collage',
      'Conceptual art',
      'Crochet',
      'Cubism',
      'Dada',
      'Digital art',
      'Embroidery',
      'Encaustic',
      'Environmental art',
      'Etching',
      'Expressionism',
      'Fauvism',
      'Furniture making',
      'Gouache',
      'Graffiti',
      'Graphite',
      'Ink',
      'Installation art',
      'Jewelry making',
      'Knitting',
      'Land art',
      'Leatherworking',
      'Letterpress',
      'Lithography',
      'Macrame',
      'Markers',
      'Metalworking',
      'Minimalism',
      'Monotype',
      'Mosaic',
      'Neo-expressionism',
      'Neo-pop',
      'Oil paint',
      'Op art',
      'Pastels',
      'Pen and ink',
      'Performance art',
      'Photography',
      'Pointillism',
      'Pop art',
      'Post-impressionism',
      'Quilting',
      'Realism',
      'Screen printing',
      'Sculpture',
      'Sign painting',
      'Spray paint',
      'Street art',
      'Surrealism',
      'Tempera',
      'Textile art',
      'Typography',
      'Video art',
      'Watercolor',
      'Weaving',
      'Woodcut',
      'Woodworking',
    ],
  },
  {
    id: 'media-types',
    name: 'Media Types',
    description: 'List of different print media types',
    chips: [
      'Advertisement',
      'Album Cover',
      'Animation',
      'Architectural Blueprint',
      'Art Book',
      'Article',
      'Billboard',
      'Book Cover',
      'Brochure',
      'Business Card',
      'Calendar',
      'Catalogue',
      'Cereal Box',
      'Comic Book',
      'Computer Game',
      'Corporate Identity',
      'Digital Painting',
      'Editorial',
      'E-Book',
      'E-Commerce Website',
      'Email Campaign',
      'Flyer',
      'Greeting Card',
      'Infographic',
      'Instagram Post',
      'Magazine Ad',
      'Magazine Cover',
      'Meme',
      'Movie Poster',
      'Newspaper Ad',
      'Pop-Up Book',
      'Poster',
      'Product Shot',
      'Promo Video',
      'Sticker',
      'T-Shirt Design',
      'Textile Design',
      'Trade Show Booth',
    ],
  },
];
