export const artistChips = {
  painters: {
    name: 'Painters',
    description: 'List of some famous painters',
    chips: [
      'Leonardo da Vinci',
      'Vincent van Gogh',
      'Pablo Picasso',
      'Michelangelo',
      'Rembrandt',
      'Claude Monet',
      'Edvard Munch',
      'Salvador Dalí',
      'Johannes Vermeer',
      'Edgar Degas',
      'Raphael',
      'Diego Velázquez',
      'Jan van Eyck',
      'Peter Paul Rubens',
      'Jan Vermeer',
      'Caravaggio',
      'Titian',
      'Albrecht Dürer',
      'Sandro Botticelli',
      'El Greco',
      'Gustav Klimt',
      'Henri Matisse',
      'Georges Seurat',
      'Édouard Manet',
      'Paul Cézanne',
      'Henri de Toulouse-Lautrec',
      'William Turner',
      'John Singer Sargent',
      'Giotto di Bondone',
      'Paul Gauguin',
      'Édgar Degas',
      'Andrea Mantegna',
      'Egon Schiele',
      'Alphonse Mucha',
      'Camille Pissarro',
      'Frida Kahlo',
      'John William Waterhouse',
      'James McNeill Whistler',
      'Hans Holbein the Younger',
      'Francisco Goya',
      'Pieter Bruegel the Elder',
      'Edward Hopper',
      'Katsushika Hokusai',
      'Francis Bacon',
      'Marc Chagall',
      'Gustave Courbet',
      'Jean-Auguste-Dominique Ingres',
      'Rogier van der Weyden',
      'Pieter Claesz',
      'Georges Braque',
      'Joan Miró',
      'Willem de Kooning',
      'Jackson Pollock',
      'Mark Rothko',
      'Henri Rousseau',
      'David Hockney',
      'Roy Lichtenstein',
      'René Magritte',
      'Amedeo Modigliani',
      'Edvard Munch',
      'Emil Nolde',
      'Odilon Redon',
      'Auguste Rodin',
      'Georges Rouault',
      'Georges-Pierre Seurat',
      'Alfred Sisley',
      'Edward Burne-Jones',
      'Jean-Francois Millet',
      'Thomas Gainsborough',
      'Gustave Moreau',
      'Jean-Baptiste-Siméon Chardin',
      'William Blake',
      'Eugène Delacroix',
      'Antoni Gaudí',
      'Fernand Léger',
      'William Morris',
      'John Constable',
      'Dante Gabriel Rossetti',
      'Frederic Leighton',
      'William Holman Hunt',
      'John Everett Millais',
      'William Bouguereau',
      'Camille Corot',
      'Émile Bernard',
      'Kazimir Malevich',
      'Gustave Caillebotte',
      'Théodore Géricault',
      'Alberto Giacometti',
      'Victor Vasarely',
      'Joseph Beuys',
      'Anselm Kiefer',
    ],
  },

  photographers: {
    name: 'Photographers',
    description: 'List of photographers',
    chips: [
      'Ansel Adams',
      'Diane Arbus',
      'Richard Avedon',
      'Robert Capa',
      'Henri Cartier-Bresson',
      'Imogen Cunningham',
      'William Eggleston',
      'Walker Evans',
      'Robert Frank',
      'Nan Goldin',
      'Lewis Hine',
      'David LaChapelle',
      'Dorothea Lange',
      'Annie Leibovitz',
      'Sally Mann',
      'Mary Ellen Mark',
      'Duane Michals',
      'László Moholy-Nagy',
      'Tina Modotti',
      'James Nachtwey',
      'Helmut Newton',
      'Gordon Parks',
      'Man Ray',
      'Irving Penn',
      'Cindy Sherman',
      'Edward Steichen',
      'Alfred Stieglitz',
      'Paul Strand',
      'W. Eugene Smith',
      'Edward Weston',
      'Minor White',
      'Joel-Peter Witkin',
      'Francesca Woodman',
      'Yousuf Karsh',
      'Lee Friedlander',
      'Nikki Lee',
      'Philip-Lorca diCorcia',
      'Andreas Gursky',
      'Gregory Crewdson',
      'Nobuyoshi Araki',
      'David Bailey',
      'Brassaï',
      'Larry Clark',
      'Hiroshi Sugimoto',
      'Stephen Shore',
      'Daido Moriyama',
      'Rineke Dijkstra',
      'Alec Soth',
      'Robert Mapplethorpe',
      'Edward Burtynsky',
      'Thomas Struth',
      'Eugene Atget',
      'Weegee',
      'Harry Callahan',
      'Lee Miller',
      'Alvin Langdon Coburn',
      'Berenice Abbott',
      'Robert Adams',
      'Eadweard Muybridge',
      'Peter Lindbergh',
      'Bruce Davidson',
      'Mary Ellen Mark',
      'Chris Killip',
      'Don McCullin',
      'Larry Fink',
      'Bruce Gilden',
      'Nan Goldin',
      'Judy Dater',
      'Ernst Haas',
      'Robert Doisneau',
      'Herb Ritts',
      'John Baldessari',
      'William Klein',
      'Martin Parr',
      'Hans Bellmer',
      'Lee Friedlander',
      'Ara Güler',
      'Zanele Muholi',
      'Roni Horn',
      'Sophie Calle',
      'Gabriele Basilico',
      'Ralph Eugene Meatyard',
      'Elliott Erwitt',
      'Steve McCurry',
      'Thomas Demand',
      'Lauren Greenfield',
      'Shirin Neshat',
      'Michael Kenna',
      'Kenro Izu',
      'Stephen Gill',
      'Trent Parke',
      'Wolfgang Tillmans',
      'Alex Webb',
      'Anton Corbijn',
      'David Goldblatt',
      'Ansel Adams',
      'Diane Arbus',
      'Richard Avedon',
      'Robert Capa',
      'Henri Cartier-Bresson',
      'Imogen Cunningham',
      'William Eggleston',
      'Walker Evans',
      'Robert Frank',
      'Nan Goldin',
      'Lewis Hine',
      'David LaChapelle',
      'Dorothea Lange',
      'Annie Leibovitz',
      'Sally Mann',
      'Mary Ellen Mark',
      'Duane Michals',
      'László Moholy-Nagy',
      'Tina Modotti',
      'James Nachtwey',
      'Helmut Newton',
      'Gordon Parks',
      'Man Ray',
      'Irving Penn',
      'Cindy Sherman',
      'Edward Steichen',
      'Alfred Stieglitz',
      'Paul Strand',
      'W. Eugene Smith',
      'Edward Weston',
      'Minor White',
      'Joel-Peter Witkin',
      'Francesca Woodman',
      'Yousuf Karsh',
      'Lee Friedlander',
      'Nikki Lee',
      'Philip-Lorca diCorcia',
      'Andreas Gursky',
      'Gregory Crewdson',
      'Nobuyoshi Araki',
      'David Bailey',
      'Brassaï',
      'Larry Clark',
      'Hiroshi Sugimoto',
      'Stephen Shore',
      'Daido Moriyama',
      'Rineke Dijkstra',
      'Alec Soth',
      'Robert Mapplethorpe',
      'Edward Burtynsky',
      'Thomas Struth',
      'Eugene Atget',
      'Weegee',
      'Harry Callahan',
      'Lee Miller',
      'Alvin Langdon Coburn',
      'Berenice Abbott',
      'Robert Adams',
      'Eadweard Muybridge',
      'Peter Lindbergh',
      'Bruce Davidson',
      'Mary Ellen Mark',
      'Chris Killip',
      'Don McCullin',
      'Larry Fink',
      'Bruce Gilden',
      'Nan Goldin',
      'Judy Dater',
      'Ernst Haas',
      'Robert Doisneau',
      'Herb Ritts',
      'John Baldessari',
      'William Klein',
      'Martin Parr',
      'Hans Bellmer',
      'Lee Friedlander',
      'Ara Güler',
      'Zanele Muholi',
      'Roni Horn',
      'Sophie Calle',
      'Gabriele Basilico',
      'Ralph Eugene Meatyard',
      'Elliott Erwitt',
      'Steve McCurry',
      'Thomas Demand',
      'Lauren Greenfield',
      'Shirin Neshat',
      'Michael Kenna',
      'Kenro Izu',
      'Stephen Gill',
      'Trent Parke',
      'Wolfgang Tillmans',
      'Alex Webb',
      'Anton Corbijn',
      'David Goldblatt',
    ],
  },
  mediums: {
    name: 'Mediums',
    description: 'List of mediums',
    chips: [
      'Acrylic',
      'Oil paint',
      'Watercolor',
      'Gouache',
      'Encaustic',
      'Tempera',
      'Ink',
      'Graphite',
      'Charcoal',
      'Pastels',
      'Colored pencils',
      'Markers',
      'Pen and ink',
      'Chalk',
      'Spray paint',
      'Airbrush',
      'Screen printing',
      'Block printing',
      'Letterpress',
      'Etching',
      'Lithography',
      'Woodcut',
      'Linocut',
      'Monotype',
      'Collage',
      'Assemblage',
      'Sculpture',
      'Ceramics',
      'Glassblowing',
      'Mosaic',
      'Textile art',
      'Embroidery',
      'Quilting',
      'Knitting',
      'Crochet',
      'Macrame',
      'Weaving',
      'Basket weaving',
      'Jewelry making',
      'Metalworking',
      'Woodworking',
      'Furniture making',
      'Leatherworking',
      'Calligraphy',
      'Typography',
      'Sign painting',
      'Graffiti',
      'Photography',
      'Digital art',
      'Video art',
      'Performance art',
      'Installation art',
      'Land art',
      'Environmental art',
      'Street art',
      'Conceptual art',
      'Pop art',
      'Abstract art',
      'Cubism',
      'Fauvism',
      'Expressionism',
      'Surrealism',
      'Dada',
      'Art nouveau',
      'Art deco',
      'Realism',
      'Impressionism',
      'Post-impressionism',
      'Pointillism',
      'Op art',
      'Minimalism',
      'Neo-expressionism',
      'Neo-pop',
      'Installation art',
      'Performance art',
      'Land art',
      'Environmental art',
      'Street art',
      'Conceptual art',
      'Pop art',
      'Abstract art',
      'Cubism',
      'Fauvism',
      'Expressionism',
      'Surrealism',
      'Dada',
      'Art nouveau',
      'Art deco',
      'Realism',
      'Impressionism',
      'Post-impressionism',
      'Pointillism',
      'Op art',
      'Minimalism',
      'Neo-expressionism',
      'Neo-pop',
    ],
  },
  mediaTypes: {
    name: 'Media Types',
    description: 'List of different print media types',
    chips: [
      'Advertisement',
      'Album Cover',
      'Animation',
      'Architectural Blueprint',
      'Art Book',
      'Article',
      'Billboard',
      'Book Cover',
      'Brochure',
      'Business Card',
      'Calendar',
      'Catalogue',
      'Cereal Box',
      'Comic Book',
      'Computer Game',
      'Corporate Identity',
      'Digital Painting',
      'Editorial',
      'E-Book',
      'E-Commerce Website',
      'Email Campaign',

      'Flyer',
      'Greeting Card',
      'Infographic',
      'Instagram Post',

      'Magazine Ad',
      'Magazine Cover',
      'Meme',
      'Movie Poster',
      'Newspaper Ad',
      'Pop-Up Book',
      'Poster',
      'Product Shot',
      'Promo Video',
      'Sticker',
      'T-Shirt Design',
      'Textile Design',
      'Trade Show Booth',
    ],
  },
};
