export const photoChips = [
  {
    id: 'cameras',
    name: 'Cameras',
    description: 'Large varitey of cameras',
    chips: [
      'Agfa Ansco Speedex',
      'Agfa Isolette',
      'Argus C3',
      'Argus C4',
      'Bronica ETRSi',
      'Bronica S2A',
      'Bronica SQ-A',
      'Canon AE-1',
      'Canon EOS R5',
      'Canon EOS Rebel 2000',
      'Canon QL17 GIII',
      'Canon T70',
      'Contax G2',
      'Contax T2',
      'Contax II',
      'Fujica ST801',
      'Fujifilm GFX 50S II',
      'Fujifilm TX-1',
      'Fujifilm X-T4',
      'Fuji GW690III',
      'Graflex Speed Graphic',
      'Hasselblad 2000FC',
      'Hasselblad 500CM',
      'Hasselblad 903SWC',
      'Hasselblad X1D II 50C',
      'Holga 120N',
      'Holga 135',
      'Kodak Brownie Hawkeye',
      'Kodak Brownie No. 2',
      'Kodak Instamatic',
      'Kodak Retina IIIc',
      'Konica Auto S3',
      'GoPro HERO9 Black camera with GoPro Super Suit Dive Housing',
      'Logitech C920 HD Pro Webcam',
      'DJI Phantom 4 Pro drone camera',
      'Lomo LC-A',
      'Lomo Lubitel 166B',
      'Leica IIIf',
      'Leica M2',
      'Leica M3',
      'Leica Q2 Monochrom',
      'Mamiya C220',
      'Mamiya RB67',
      'Minolta Hi-Matic 7S',
      'Minolta SRT-101',
      'Nikon EM',
      'Nikon F3',
      'Nikon FM2',
      'Nikon N80',
      'Nikon SP',
      'Nikon Z7 II',
      'Nishika N8000',
      'Olympus OM-1',
      'Olympus OM-D E-M10 Mark IV',
      'Olympus Trip 35',
      'Pentax 645N',
      'Pentax Espio Mini',
      'Pentax K1000',
      'Pentax K2',
      'Pentax MX',
      'Pentax Spotmatic',
      'Polaroid 600',
      'Polaroid Land Camera 250',
      'Polaroid SX-70',
      'Polaroid SX-70 Sonar',
      'Ricoh GR III',
      'Rollei 35',
      'Rolleiflex 2.8F',
      'Rolleiflex T',
      'Sony Alpha A7 III',
      'Voigtländer Bessa R2M',
      'Yashica Electro 35',
      'Yashica Mat-124G',
      'Yashica T4',
      'Zeiss Ikon Contax IIIa',
      'Zeiss Ikon Contax II',
    ],
  },
  {
    id: 'lens',
    name: 'Camera Lenses',
    description: 'Defines camera lens types',
    chips: [
      'Canon EF 100mm f/2.8L Macro lens',
      'Canon EF 8-15mm f/4L Fisheye USM lens',
      'Canon EF 24-70mm f/2.8L II USM lens',
      'Canon EF 100mm f/2.8L Macro IS USM lens',
      'Canon EF 16-35mm f/2.8L III USM lens',
      'Canon EF 50mm f/1.2L USM lens',
      ' Nikkor 70-200mm f/2.8E FL ED VR lens',
      'Panasonic Lumix 12-35mm f/2.8 II lens',
      'Canon EF 70-200mm f/2.8L IS III USM lens',
      'Canon EF 14mm f/2.8L II USM lens',
      'Nikkor 24-70mm f/2.8E ED VR lens',
      'Sony FE 16-35mm f/2.8 GM lens',
      'Sony FE 24-105mm f/4 G OSS lens',
    ],
  },
  {
    id: 'filmTypes',
    name: 'Film Types',
    description: 'Variety of films and ISOs',
    chips: [
      'Kodachrome',
      'Kodak Ektar 25',
      'Kodak Ektar 100',
      'Kodak Ektar 125',
      'Kodak Ektar 400',
      'Kodak Gold 100',
      'Kodak Gold 200',
      'Kodak Gold 400',
      'Kodak Portra 160',
      'Kodak Portra 400',
      'Kodak Portra 800',
      'Kodak T-Max 100',
      'Kodak T-Max 400',
      'Kodak Tri-X 400',
      'Kodak Ultramax 400',
      'Kodak Vision3 50D',
      'Kodak Vision3 200T',
      'Kodak Vision3 500T',
      'Fujifilm Acros 100',
      'Fujifilm Neopan 100 Acros',
      'Fujifilm Pro 160NS',
      'Fujifilm Pro 400H',
      'Fujifilm Provia 100F',
      'Fujifilm Velvia 50',
      'Fujifilm Velvia 100',
      'Fujifilm Superia 100',
      'Fujifilm Superia 200',
      'Fujifilm Superia 400',
      'Ilford Delta 100',
      'Ilford Delta 3200',
      'Ilford FP4 Plus 125',
      'Ilford HP5 Plus 400',
      'Ilford Pan F Plus 50',
      'Ilford XP2 Super 400',
      'Ilford SFX 200',
      'Ilford Ortho Plus 80',
      'Ilford Delta 400',
      'Ilford Delta 100 Professional',
      'Ilford Delta 400 Professional',
      'Ilford Delta 3200 Professional',
      'Ilford FP4 Plus 125 Professional',
      'Ilford HP5 Plus 400 Professional',
      'Ilford Pan F Plus 50 Professional',
      'Ilford Ortho Ortho Plus 80 Professional',
      'Ilford SFX 200 Professional',
    ],
  },

  {
    id: 'angles',
    name: 'Camera Angles',
    description: 'Variety of camera angles',
    chips: [
      'Underwater Close-Up Shot',
      'Underwater Shot',
      'GoPro-Style',
      'Webcam-Style Shot',
      'Aerial Shot (Bird’s-Eye View)',
      'Ground-Level Shot',
      'Extreme Close-Up Shot',
      'Full shot',
      'Medium shot',
      'Close-up shot',
      'Shot from Behind',
      'Side-Angle (Side-View)',
      'Extreme high-angle shot',
      'Extreme low-angle shot',
      'High-Angle Shot',
      'Low-Angle Shot',
      'Eye-Level Shot',
    ],
  },
  {
    id: 'weather',
    name: 'Weather and Lighting',
    description: 'Weather and lighting conditions',
    chips: [
      'Sunny',
      'Partly Cloudy',
      'Rainy',
      'Snowy',
      'Overcast',
      'Foggy',
      'Hazy',
      'Thunderstorm',
      'Blizzard',
      'Tornado',
      'Hurricane',
      'Sleet',
      'Mist',
      'Drizzle',
      'Squall',
      'Sandstorm',
      'Duststorm',
      'Heatwave',
      'Coldwave',
      'Icy',
    ],
  },

  {
    id: 'timeOfDay',
    name: 'Time of Day',
    description: 'Different moods from time of day',
    chips: [
      'Sunrise',
      'Morning',
      'Afternoon',
      'Golden Hour',
      'Sunset',
      'Twilight',
      'Night',
      'Blue hour',
      'Dusk',
    ],
  },

  {
    id: 'ambiance',
    name: 'Ambiance',
    description: 'Set the mood',
    chips: [
      'Dark and Moody',
      'Bright and Vibrant',
      'Fantasy',
      'Historical',
      'Adventure/Action',
      'Documentary',
      'Horror',
      'Mystical',
      'Romantic',
      'Rustic',
      'Minimalistic',
      'Futuristic',
      'Gritty',
      'Surreal',
      'Saturated',
      'Pastel',
      'Noir',
      'Gothic',
      'Glamorous',
      'Industrial',
      'Bohemian',
    ],
  },
];
