export const critterChips = [
  {
    id: 'animals',
    name: 'Animals',
    description: 'List of differeant critters',
    chips: [
      'Aardvark',
      'Alpaca',
      'Antelope',
      'Armadillo',
      'Baboon',
      'Badger',
      'Bat',
      'Bear',
      'Beaver',
      'Bison',
      'Buffalo',
      'Camel',
      'Capybara',
      'Caribou',
      'Cat',
      'Cheetah',
      'Chimpanzee',
      'Chinchilla',
      'Chipmunk',
      'Cow',
      'Coyote',
      'Deer',
      'Dog',
      'Dolphin',
      'Donkey',
      'Elephant',
      'Elk',
      'Ferret',
      'Fox',
      'Gazelle',
      'Giraffe',
      'Goat',
      'Gorilla',
      'Groundhog',
      'Guinea pig',
      'Hamster',
      'Hedgehog',
      'Hippopotamus',
      'Horse',
      'Hyena',
      'Jaguar',
      'Kangaroo',
      'Koala',
      'Lemur',
      'Leopard',
      'Lion',
      'Llama',
      'Marmot',
      'Meerkat',
      'Moose',
      'Mouse',
      'Ocelot',
      'Octopus',
      'Opossum',
      'Orangutan',
      'Otter',
      'Panda',
      'Pangolin',
      'Penguin',
      'Pig',
      'Polar bear',
      'Porcupine',
      'Possum',
      'Puma',
      'Rabbit',
      'Raccoon',
      'Rat',
      'Red panda',
      'Reindeer',
      'Rhinoceros',
      'Seal',
      'Sheep',
      'Shrew',
      'Sloth',
      'Squirrel',
      'Tiger',
      'Walrus',
      'Weasel',
      'Whale',
      'Wolf',
      'Wolverine',
      'Wombat',
      'Woodchuck',
      'Yak',
      'Zebra',
    ],
  },
  {
    id: 'birds',
    name: 'Birds',
    description: 'List of differeant bird species',
    chips: [
      'American Goldfinch',
      'American Robin',
      'Bald Eagle',
      'Barn Owl',
      'Barred Owl',
      'Black-capped Chickadee',
      'Black-throated Sparrow',
      'Blue Jay',
      'Blue Tit',
      'Brown Pelican',
      'California Condor',
      'Canada Goose',
      'Cape May Warbler',
      'Cardinal',
      'Carolina Wren',
      'Cedar Waxwing',
      'Chaffinch',
      'Chimney Swift',
      'Common Loon',
      'Common Redpoll',
      'Cormorant',
      'Crested Caracara',
      'Crowned Eagle',
      'Eagle Owl',
      'Eastern Bluebird',
      'Eastern Meadowlark',
      'Egyptian Vulture',
      'Eurasian Magpie',
      'European Robin',
      'Flamingo',
      'Gila Woodpecker',
      'Golden Eagle',
      'Golden Pheasant',
      'Great Blue Heron',
      'Great Grey Owl',
      'Great Horned Owl',
      'Green Jay',
      'Green-winged Teal',
      'Harpy Eagle',
      'Hawk',
      'Herring Gull',
      'Hoatzin',
      'Hooded Merganser',
      'Hoopoe',
      'Horned Lark',
      'House Sparrow',
      'House Wren',
      'Hummingbird',
      'Ibis',
      'Jabiru',
      'Killdeer',
      'Kingfisher',
      'Kookaburra',
      'Lapwing',
      'Lark Bunting',
      'Laughing Gull',
      'Laysan Albatross',
      'Little Egret',
      'Magnificent Frigatebird',
      'Mallard',
      'Manx Shearwater',
      'Mourning Dove',
      'Nighthawk',
      'Northern Cardinal',
      'Northern Flicker',
      'Northern Harrier',
      'Osprey',
      'Ostrich',
      'Owl',
      'Painted Bunting',
      'Penguin',
      'Peregrine Falcon',
      'Piping Plover',
      'Puffin',
      'Purple Martin',
      'Red-bellied Woodpecker',
      'Red-breasted Nuthatch',
      'Red-tailed Hawk',
      'Ring-necked Pheasant',
      'Roadrunner',
      'Rock Ptarmigan',
      'Roseate Spoonbill',
      'Ruby-throated Hummingbird',
      'Ruffed Grouse',
      'Sanderling',
      'Sandhill Crane',
      'Savannah Sparrow',
      'Scissor-tailed Flycatcher',
      'Snowy Egret',
      'Snowy Owl',
      'Spotted Sandpiper',
      "Steller's Jay",
      'Swallow-tailed Kite',
      'Swan',
      'Toucan',
      'Turkey Vulture',
      'Upland Sandpiper',
      'Violet-green Swallow',
      'Wandering Albatross',
      'White Pelican',
      'Whooping Crane',
      'Wild Turkey',
      "Wilson's Plover",
      'Wood Duck',
      'Wood Thrush',
      'Woodpecker',
      'Wrentit',
      'Yellow Warbler',
    ],
  },
  {
    id: 'marine',
    name: 'Marine Creatures',
    description: 'Different species from the ocean',
    chips: [
      'Blue whale',
      'Great white shark',
      'Giant squid',
      'Orca',
      'Jellyfish',
      'Green sea turtle',
      'Clownfish',
      'Octopus',
      'Narwhal',
      'Humpback whale',
      'Dolphin',
      'Hammerhead shark',
      'Sperm whale',
      'Lionfish',
      'Sea otter',
      'Manta ray',
      'Seahorse',
      'Swordfish',
      'Goliath grouper',
      'Gray whale',
      'Manatee',
      'Walrus',
      'Giant clam',
      'Moray eel',
      'Cuttlefish',
      'Sea dragon',
      'Sea urchin',
      'Stingray',
      'Nautilus',
      'Barracuda',
      'Horseshoe crab',
      'Giant isopod',
      'Sea cucumber',
      'Lobster',
      'Giant oarfish',
      'Box jellyfish',
      'Megalodon',
      'Leatherback sea turtle',
      'Beluga whale',
      'Goblin shark',
      'Kraken',
      'Sea anemone',
      'Blacktip reef shark',
      'Coral',
      "Portuguese man o' war",
      'Dugong',
      'Blobfish',
      'Squid',
      'Frilled shark',
      'Rockfish',
      'Nudibranch',
      'Giant octopus',
      'Chambered nautilus',
      'Anemone crab',
      'Vampire squid',
      'Oyster',
      'Shrimp',
      'Blue tang',
      'Electric eel',
      'Sea star',
      'Loggerhead sea turtle',
      'Sea lion',
      'Cownose ray',
      'Chimaera',
      'Sea moth',
      'Tuna',
      'Giant tube worm',
      'Sea snake',
      'Giant spider crab',
      'Sardine',
      'Sea bass',
      'Mackerel',
      'King crab',
      'Penguin',
      'Crayfish',
      'Pufferfish',
      'Sea sponge',
      'Spider conch',
      'Giant kelp',
      'Scallop',
      'Porpoise',
      'Bryozoan',
      'Clam',
      'Periwinkle',
      'Sea lily',
      'Pelican',
      'Sand dollar',
      'Comb jelly',
      'Jellyfish tree',
      'Sea slug',
      'Sea bream',
      'Hagfish',
      'Sea urchin roe',
      'Squid ink',
      'Gelatinous zooplankton',
      'Sailfish',
      'Seadragon',
      'Flounder',
      'Lamprey',
      'Sea serpent',
      'Flying fish',
      'Bonito',
      'Turtle',
      'Haddock',
      'Salmon',
      'Bass',
      'Sockeye salmon',
      'Swordtail',
      'Milkfish',
      'Pike',
      'Tilapia',
      'Wahoo',
      'Trout',
      'Tuna fish',
      'Tetra',
      'Mahi-mahi',
      'Grouper',
      'Barramundi',
    ],
  },
  {
    id: 'mytho',
    name: 'Mythological Creatures',
    description: 'List of beasts from fantasy and mythology',
    chips: [
      'Dragon',
      'Unicorn',
      'Minotaur',
      'Sphinx',
      'Kraken',
      'Phoenix',
      'Chimera',
      'Cerberus',
      'Manticore',
      'Harpy',
      'Basilisk',
      'Hydra',
      'Centaur',
      'Gorgon',
      'Pegasus',
      'Cyclops',
      'Faun',
      'Satyr',
      'Mermaid',
      'Werewolf',
      'Vampire',
      'Zombie',
      'Ghost',
      'Ghoul',
      "Frankenstein's monster",
      'Mummy',
      'Siren',
      'Griffin',
      'Hippogriff',
      'Ent',
      'Balrog',
      'Orc',
      'Troll',
      'Goblin',
      'Dwarf',
      'Elf',
      'Naga',
      'Yeti',
      'Bigfoot',
      'Chupacabra',
      'Thunderbird',
      'Mothman',
      'Jersey Devil',
      'Loch Ness Monster',
      'Kappa',
      'Oni',
      'Kitsune',
      'Tanuki',
      'Raiju',
      'Qilin',
      'Nian',
      'Tengu',
      'Bakeneko',
      'Yuki-onna',
      'Chōchin-obake',
      'Jorogumo',
      'Kamaitachi',
      'Kirin',
      'Zashiki-warashi',
      'Bunyip',
      'Drop bear',
      'Yowie',
      'Taniwha',
      'Menehune',
      'Nāga',
      'Tupilaq',
      'Ahuitzotl',
      'Camazotz',
      'Cihuateteo',
      'Coatlicue',
      'Tlaltecuhtli',
      'Xolotl',
      'Ahuizotl',
      'Chaneque',
      'Coyolxauhqui',
      'Itzpapalotl',
      'Mictlantecuhtli',
      'Tezcatlipoca',
      'Tlazolteotl',
      'Chimalli',
      'Mam',
      'Quetzalcoatl',
      'Sipapu',
      'Horned serpent',
      'Thunderbird',
      'Manitu',
      'Inua',
      'Pukwudgie',
      'Wendigo',
      'Thunderbird',
      'Shaman',
      'Medusa',
      'Scylla',
      'Caryatid',
      'Nereid',
      'Siren',
      'Kraken',
      'Cockatrice',
      'Charybdis',
      'Merrow',
      'Selkie',
      'Kelpie',
      'Nuckelavee',
      'Phoenix',
      'Thunderbird',
      'Frost giant',
      'Fire giant',
      'Troll',
      'Dwarf',
      'Elf',
      'Hobbit',
      'Ent',
      'Orc',
      'Goblin',
      'Gnome',
      'Imp',
      'Leviathan',
      'Behemoth',
      'Unicorn',
      'Thunderbird',
      'Peryton',
      'Wyvern',
      'Banshee',
      'Changeling',
    ],
  },
  {
    id: 'dNd',
    name: 'D&D Creatures',
    description: 'From the monster manual',
    chips: [
      'Aboleth',
      'Achaierai',
      'Ankheg',
      'Azer',
      'Basilisk',
      'Behir',
      'Beholder',
      'Bulette',
      'Chimera',
      'Cloaker',
      'Cockatrice',
      'Darkmantle',
      'Death Knight',
      'Demilich',
      'Displacer Beast',
      'Djinni',
      'Doppelganger',
      'Dragon Turtle',
      'Drider',
      'Ettercap',
      'Ettin',
      'Flumph',
      'Frost Giant',
      'Gargoyle',
      'Genie',
      'Ghoul',
      'Gibbering Mouther',
      'Githyanki',
      'Githzerai',
      'Gnoll',
      'Gorgon',
      'Gremlin',
      'Grick',
      'Griffon',
      'Harpy',
      'Hell Hound',
      'Hippogriff',
      'Hook Horror',
      'Hydra',
      'Intellect Devourer',
      'Invisible Stalker',
      'Kraken',
      'Lamia',
      'Lich',
      'Lizard King',
      'Lizard Man',
      'Manticore',
      'Medusa',
      'Mimic',
      'Mind Flayer',
      'Minotaur',
      'Mummy',
      'Naga',
      'Ochre Jelly',
      'Ogre',
      'Owlbear',
      'Pegasus',
      'Phase Spider',
      'Pseudodragon',
      'Purple Worm',
      'Rakshasa',
      'Remorhaz',
      'Roc',
      'Roper',
      'Rust Monster',
      'Sahuagin',
      'Salamander',
      'Satyr',
      'Shadow',
      'Shambling Mound',
      'Siren',
      'Skeleton',
      'Spectator',
      'Sphinx',
      'Stirge',
      'Succubus',
      'Tarrasque',
      'Troll',
      'Umber Hulk',
      'Unicorn',
      'Vampire',
      'Vrock',
      'Water Weird',
      'Werewolf',
      'Wight',
      "Will-o'-Wisp",
      'Wraith',
      'Wyvern',
      'Xorn',
      'Yeti',
      'Yuan-ti',
      'Zombie',
    ],
  },
];
