export const genreChips = [
  {
    id: 'movies',
    name: 'Movies',
    description: 'List of some movies with distinct styles',
    chips: [
      '2001: A Space Odyssey',
      '8 1/2',
      'Amélie',
      'American Beauty',
      'Annie Hall',
      'Apocalypse Now',
      'Avatar',
      'A Clockwork Orange',
      'A Fistful of Dollars',
      'Autumn Sonata',
      'Battleship Potemkin',
      'Beauty and the Beast',
      'Blade Runner',
      'Bonnie and Clyde',
      'Breathless',
      'Chinatown',
      'City Lights',
      'Cries and Whispers',
      'Crouching Tiger, Hidden Dragon',
      'Do the Right Thing',
      'Dracula',
      'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
      'For a Few Dollars More',
      'Fanny and Alexander',
      'Gone with the Wind',
      'Goodfellas',
      'Gravity',
      'Ikiru',
      'Intolerance',
      'Jaws',
      'JFK',
      'La Dolce Vita',
      'La Grande Illusion',
      'Lawrence of Arabia',
      'M',
      'Metropolis',
      'Modern Times',
      'Nosferatu',
      'Once Upon a Time in the West',
      "One Flew Over the Cuckoo's Nest",
      'Persona',
      'Platoon',
      'Psycho',
      'Pulp Fiction',
      'Raging Bull',
      'Ran',
      'Rome, Open City',
      'Saving Private Ryan',
      'Scenes from a Marriage',
      "Schindler's List",
      "Singin' in the Rain",
      'Star Wars: Episode IV - A New Hope',
      'Taxi Driver',
      'The Bicycle Thief',
      'The Birth of a Nation',
      'The Bridge on the River Kwai',
      'The Cabinet of Dr. Caligari',
      'The Exorcist',
      'The French Connection',
      'The General',
      'The Godfather',
      'The Gold Rush',
      'The Good, the Bad and the Ugly',
      'The Graduate',
      'The Hidden Fortress',
      'The Lord of the Rings: The Fellowship of the Ring',
      'The Magnificent Seven',
      'The Maltese Falcon',
      'The Matrix',
      'The Passion of Anna',
      'The Passion of Joan of Arc',
      'The Revenant',
      'The Searchers',
      'The Seventh Seal',
      'The Shining',
      'The Silence of the Lambs',
      'The Third Man',
      'Through a Glass Darkly',
      'Throne of Blood',
      'Touch of Evil',
      'Vertigo',
      'Wild Strawberries',
      'Winter Light',
      'Yojimbo',
    ],
  },
  {
    id: 'directors',
    name: 'Directors',
    description: 'List of some directors with distinct styles',
    chips: [
      'Akira Kurosawa',
      'Abbas Kiarostami',
      'Alejandro González Iñárritu',
      'Alfred Hitchcock',
      'Andrei Tarkovsky',
      'Ava DuVernay',
      'Barry Jenkins',
      'Béla Tarr',
      'Bertrand Tavernier',
      'Billy Wilder',
      'Blake Edwards',
      'Céline Sciamma',
      'Christopher Nolan',
      'Claude Chabrol',
      'Coen Brothers',
      'Danny Boyle',
      'Darren Aronofsky',
      'David Fincher',
      'David Lynch',
      'F.W. Murnau',
      'Federico Fellini',
      'Federico Fellini',
      'François Ozon',
      'François Truffaut',
      'Frank Capra',
      'Gaspar Noé',
      'Gaspar Noé',
      'Greta Gerwig',
      'Guillermo del Toro',
      'Guy Ritchie',
      'Hayao Miyazaki',
      'Hirokazu Kore-eda',
      'Howard Hawks',
      'Ingmar Bergman',
      'Jacques Audiard',
      'Jacques Tati',
      'James Cameron',
      'James Whale',
      'Jean Cocteau',
      'Jean-Jacques Annaud',
      'Jean-Luc Godard',
      'Jean-Pierre Jeunet',
      'Jean-Pierre Melville',
      'Jim Jarmusch',
      'John Carpenter',
      'John Ford',
      'John Huston',
      'John Woo',
      'Jordan Peele',
      'Kathryn Bigelow',
      'Lars von Trier',
      'Leos Carax',
      'Louis Malle',
      'Luc Besson',
      'Luchino Visconti',
      'Lynne Ramsay',
      'Marcel Carné',
      'Martin Scorsese',
      'Mia Hansen-Løve',
      'Michel Gondry',
      'Michelangelo Antonioni',
      'Mike Nichols',
      'Oliver Stone',
      'Orson Welles',
      'Park Chan-wook',
      'Patrice Leconte',
      'Paul Thomas Anderson',
      'Peter Jackson',
      'Richard Linklater',
      'Ridley Scott',
      'Robert Altman',
      'Robert Bresson',
      'Robert Rodriguez',
      'Roman Polanski',
      'Ryan Coogler',
      'Sidney Lumet',
      'Sion Sono',
      'Sofia Coppola',
      'Sofia Coppola',
      'Spike Jonze',
      'Spike Lee',
      'Stanley Donen',
      'Stanley Kubrick',
      'Steve McQueen',
      'Steven Spielberg',
      'Taika Waititi',
      'Terrence Malick',
      'Terry Gilliam',
      'Takeshi Kitano',
      'Tim Burton',
      'Todd Haynes',
      'Tony Scott',
      'Wes Anderson',
      'Wim Wenders',
      'Yorgos Lanthimos',
    ],
  },
  {
    id: 'comicCharacters',
    name: 'Comic Book Characters',
    description: 'List of some famous comic book characters',
    chips: [
      'Adam Warlock',
      'Ant-Man',
      'Aquaman',
      'Atrocitus',
      'Atom',
      'Bane',
      'Baron Zemo',
      'Batman',
      'Black Adam',
      'Black Widow',
      'Blade',
      'Brainiac',
      'Captain America',
      'Catwoman',
      'Carnage',
      'Cyclops',
      'Cyborg',
      'Daredevil',
      'Darkseid',
      'Deadpool',
      'Deadshot',
      'Deathstroke',
      'Doctor Doom',
      'Doctor Strange',
      'Enchantress',
      'Falcon',
      'Flash',
      'Galactus',
      'Gambit',
      'Ghost Rider',
      'Green Arrow',
      'Green Lantern',
      'Harley Quinn',
      'Hawkeye',
      'Hellboy',
      'Hulk',
      'Iron Fist',
      'Iron Man',
      'Jean Grey',
      'Jessica Jones',
      'Joker',
      'Juggernaut',
      'Killer Croc',
      'Kingpin',
      'Kraven the Hunter',
      'Lex Luthor',
      'Luke Cage',
      'Magneto',
      'Martian Manhunter',
      'Mister Sinister',
      'Moon Knight',
      'Morbius',
      'Ms. Marvel',
      'Mysterio',
      'Namor',
      'Nightcrawler',
      'Omega Red',
      'Penguin',
      'Poison Ivy',
      'Professor X',
      'Riddler',
      "Ra's al Ghul",
      'Red Skull',
      'Rogue',
      'Sabretooth',
      'Sandman',
      'Scarecrow',
      'Shazam',
      'She-Hulk',
      'Silver Surfer',
      'Sinestro',
      'Spawn',
      'Spider-Man',
      'Storm',
      'Superman',
      'Swamp Thing',
      'Thanos',
      'The Tick',
      'Thor',
      'Two-Face',
      'Ultron',
      'Venom',
      'Vision',
      'Wasp',
      'Wolverine',
      'Wonder Woman',
      'Zatanna',
    ],
  },
  {
    id: 'comicArtists',
    name: 'Comic Book Artists',
    description: 'List of some famous comic book artists',
    chips: [
      'Adrian Tomine',
      'Akira Toriyama',
      'Alan Moore',
      'Alison Bechdel',
      'Alex Ross',
      'Art Spiegelman',
      'Arthur Adams',
      'Barry Windsor-Smith',
      'Bill Sienkiewicz',
      'Brian Bolland',
      'Brian K. Vaughan',
      'Brian Michael Bendis',
      'Charles Burns',
      'CLAMP',
      'Colleen Doran',
      'Dan Jurgens',
      'Daniel Clowes',
      'Darwyn Cooke',
      'Dave Gibbons',
      'Dave Sim',
      'Dave Stevens',
      'David Finch',
      'David Mazzucchelli',
      'Eiichiro Oda',
      'Erik Larsen',
      'Frank Brunner',
      'Frank Cho',
      'Frank Miller',
      'Frank Quitely',
      'Gail Simone',
      'Garth Ennis',
      'Gary Panter',
      'Gene Luen Yang',
      'George Pérez',
      'Gil Kane',
      'Gilbert Hernandez',
      'Hajime Isayama',
      'Harvey Pekar',
      'Herb Trimpe',
      'Jack Kirby',
      'Jaime Hernandez',
      'Jeff Lemire',
      'Jeff Smith',
      'J.H. Williams III',
      'Jim Lee',
      'Jim Starlin',
      'Jim Steranko',
      'Jim Woodring',
      'Jill Thompson',
      'Joe Kubert',
      'Joe Madureira',
      'Joe Sacco',
      'John Buscema',
      'John Byrne',
      'John Romita Jr.',
      'John Romita Sr.',
      'John Severin',
      'John Totleben',
      'Marc Silvestri',
      'Mark Bagley',
      'Mark Millar',
      'Mark Waid',
      'Masashi Kishimoto',
      'Matt Fraction',
      'Matt Wagner',
      'Michael Golden',
      'Mike Allred',
      'Mike Grell',
      'Mike Mignola',
      'Mike Ploog',
      'Mike Zeck',
      'Moto Hagio',
      'Naoki Urasawa',
      'Neal Adams',
      'Neil Gaiman',
      'Osamu Tezuka',
      'P. Craig Russell',
      'Paul Pope',
      'Richard Corben',
      'Rick Remender',
      'Rob Liefeld',
      'R. Crumb',
      'Robert Kirkman',
      'Ronin Studios',
      'Roy Thomas',
      'Rumiko Takahashi',
      'Scott Snyder',
      'Shigeru Mizuki',
      'Stan Lee',
      'Stan Sakai',
      'Steve Dillon',
      'Steve Ditko',
      'Takehiko Inoue',
      'Terry Moore',
      'Tim Sale',
      'Todd McFarlane',
      'Todd Nauck',
      'Trina Robbins',
      'Wendy Pini',
      'Whilce Portacio',
      'Will Eisner',
    ],
  },
];
