export const mediaChips = {
  comics: {
    name: 'Comic Book Characters',
    description: 'List of some famous comic book characters',
    chips: [
      'Spider-Man',
      'Batman',
      'Superman',
      'Wonder Woman',
      'Captain America',
      'Iron Man',
      'The Hulk',
      'Thor',
      'Black Widow',
      'Wolverine',
      'Cyclops',
      'Jean Grey',
      'Rogue',
      'Gambit',
      'Storm',
      'Nightcrawler',
      'Colossus',
      'Deadpool',
      'Doctor Strange',
      'Hawkeye',
      'Black Panther',
      'Ant-Man',
      'The Wasp',
      'Vision',
      'Scarlet Witch',
      'Falcon',
      'Daredevil',
      'Luke Cage',
      'Iron Fist',
      'Jessica Jones',
      'The Punisher',
      'Green Lantern',
      'The Flash',
      'Aquaman',
      'Martian Manhunter',
      'Green Arrow',
      'The Atom',
      'Zatanna',
      'Shazam',
      'Cyborg',
      'Swamp Thing',
      'The Sandman',
      'John Constantine',
      'Deathstroke',
      'Harley Quinn',
      'Joker',
      'Lex Luthor',
      'Catwoman',
      'Penguin',
      'Riddler',
      'Two-Face',
      'Scarecrow',
      'Poison Ivy',
      'Bane',
      "Ra's al Ghul",
      'Deadshot',
      'Enchantress',
      'Killer Croc',
      'Black Adam',
      'Sinestro',
      'Atrocitus',
      'Brainiac',
      'Darkseid',
      'Thanos',
      'Doctor Doom',
      'Magneto',
      'Galactus',
      'Apocalypse',
      'Ultron',
      'Red Skull',
      'Baron Zemo',
      'Kingpin',
      'Mysterio',
      'Kraven the Hunter',
      'Venom',
      'Carnage',
      'Mister Sinister',
      'Juggernaut',
      'Sabretooth',
      'Omega Red',
      'Silver Surfer',
      'Adam Warlock',
      'Namor',
      'She-Hulk',
      'Ms. Marvel',
      'Moon Knight',
      'Ghost Rider',
      'Blade',
      'Morbius',
      'Spawn',
      'Hellboy',
      'The Tick',
    ],
  },
  comicArtists: {
    name: 'Comic Book Artists',
    description: 'List of some famous comic book artists',
    chips: [
      'Jack Kirby',
      'Stan Lee',
      'Steve Ditko',
      'Will Eisner',
      'Frank Miller',
      'Alan Moore',
      'Dave Gibbons',
      'Neal Adams',
      'Jim Steranko',
      'John Buscema',
      'John Romita Sr.',
      'John Romita Jr.',
      'Todd McFarlane',
      'George Pérez',
      'Bernie Wrightson',
      'Mike Mignola',
      'Brian Bolland',
      'J.H. Williams III',
      'Frank Frazetta',
      'Gil Kane',
      'Steve Dillon',
      'Dave Stevens',
      'Jim Lee',
      'David Mazzucchelli',
      'Alex Ross',
      'Bill Sienkiewicz',
      'Jill Thompson',
      "Kevin O'Neill",
      'Paul Pope',
      'Darwyn Cooke',
      'Jeff Smith',
      'Adrian Tomine',
      "Bryan Lee O'Malley",
      'John Byrne',
      'Frank Cho',
      'Mike Allred',
      'Arthur Adams',
      'John Cassaday',
      'Frank Quitely',
      'Trina Robbins',
      'Colleen Doran',
      'Marc Silvestri',
      'David Finch',
      'Terry Moore',
      'Tim Sale',
      'J. Scott Campbell',
      'Joe Madureira',
      'Mark Bagley',
      'Mark Waid',
      'Ed Brubaker',
      'Brian Michael Bendis',
      'Grant Morrison',
      'Garth Ennis',
      'Warren Ellis',
      'Neil Gaiman',
      'Geoff Johns',
      'Mark Millar',
      'Matt Fraction',
      'Rick Remender',
      'Scott Snyder',
      'Gail Simone',
      'Kelly Sue DeConnick',
      'Jeff Lemire',
      'Robert Kirkman',
      'Brian K. Vaughan',
      'Gene Luen Yang',
      'Art Spiegelman',
      'Joe Sacco',
      'Harvey Pekar',
      'Alison Bechdel',
      'Marjane Satrapi',
      'Osamu Tezuka',
      'Akira Toriyama',
      'Naoki Urasawa',
      'Rumiko Takahashi',
      'Hajime Isayama',
      'Masashi Kishimoto',
      'Eiichiro Oda',
      'Takehiko Inoue',
      'CLAMP',
      'Stan Sakai',
      'Moto Hagio',
      'Shigeru Mizuki',
      'R. Crumb',
      'Daniel Clowes',
      'Jim Woodring',
      'Gary Panter',
      'Charles Burns',
      'Jaime Hernandez',
      'Gilbert Hernandez',
      'Dave Sim',
      'Wendy Pini',
      'Richard Corben',
      'Mike Ploog',
      'John Totleben',
      'P. Craig Russell',
      'Barry Windsor-Smith',
      'Michael Golden',
      'Mike Zeck',
      'Whilce Portacio',
      'Jim Starlin',
      'Dan Jurgens',
      'Rob Liefeld',
      'Todd Nauck',
      'Erik Larsen',
      'Matt Wagner',
      'Mike Grell',
      'John Byrne',
      'Frank Brunner',
      'Herb Trimpe',
      'John Severin',
      'John Romita Sr.',
      'John Romita Jr.',
      'Marie Severin',
      'Joe Kubert',
      'Gil Kane',
    ],
  },
  moives: {
    name: 'Movies',
    description: 'List of some movies with distinct styles',
    chips: [
      '2001: A Space Odyssey',
      'The Cabinet of Dr. Caligari',
      'Citizen Kane',
      'Blade Runner',
      'The Godfather',
      'Vertigo',
      'Lawrence of Arabia',
      'The Searchers',
      'Taxi Driver',
      'The Graduate',
      'Raging Bull',
      'Chinatown',
      'Star Wars: Episode IV - A New Hope',
      'Apocalypse Now',
      'Gone with the Wind',
      'The Good, the Bad and the Ugly',
      'Bonnie and Clyde',
      'The Wild Bunch',
      'Jaws',
      'Psycho',
      'The Shining',
      'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
      'The Matrix',
      'Do the Right Thing',
      'Saving Private Ryan',
      'Amélie',
      'Crouching Tiger, Hidden Dragon',
      "Singin' in the Rain",
      'Lawrence of Arabia',
      'The Maltese Falcon',
      'The Wizard of Oz',
      'Touch of Evil',
      'The Third Man',
      'The Bridge on the River Kwai',
      'The Seventh Seal',
      'Breathless',
      'A Clockwork Orange',
      "One Flew Over the Cuckoo's Nest",
      'A Streetcar Named Desire',
      'Annie Hall',
      'Dracula',
      'Nosferatu',
      'Metropolis',
      'Battleship Potemkin',
      'The Birth of a Nation',
      'Intolerance',
      'The Gold Rush',
      'Modern Times',
      'City Lights',
      'The General',
      'The Great Dictator',
      'Sunrise: A Song of Two Humans',
      'The Passion of Joan of Arc',
      'The Battleship Potemkin',
      'The Cabinet of Dr. Caligari',
      'M',
      'The Grand Illusion',
      'La Grande Illusion',
      'Beauty and the Beast',
      'The Seven Samurai',
      'Ran',
      'Yojimbo',
      'Ikiru',
      'The Hidden Fortress',
      'Rashomon',
      'Throne of Blood',
      'The Magnificent Seven',
      'The Good, the Bad and the Ugly',
      'For a Few Dollars More',
      'A Fistful of Dollars',
      'Once Upon a Time in the West',
      'Rome, Open City',
      'La Dolce Vita',
      '8 1/2',
      'The Bicycle Thief',
      'Persona',
      'Wild Strawberries',
      'Cries and Whispers',
      'The Seventh Seal',
      'Winter Light',
      'Through a Glass Darkly',
      'Fanny and Alexander',
      'Scenes from a Marriage',
      'The Virgin Spring',
      'Hour of the Wolf',
      'The Passion of Anna',
      'Autumn Sonata',
      'The Exorcist',
      'The French Connection',
      'JFK',
      'Platoon',
      "Schindler's List",
      'Goodfellas',
      'Pulp Fiction',
      'The Silence of the Lambs',
      'American Beauty',
      'The Matrix',
      'The Lord of the Rings: The Fellowship of the Ring',
      'Avatar',
      'Gravity',
      'The Revenant',
    ],
  },
  directors: {
    name: 'Directors',
    description: 'List of some directors with distinct styles',
    chips: [
      'Quentin Tarantino',
      'Stanley Kubrick',
      'Alfred Hitchcock',
      'Martin Scorsese',
      'Francis Ford Coppola',
      'Steven Spielberg',
      'Christopher Nolan',
      'Tim Burton',
      'David Lynch',
      'Spike Lee',
      'Darren Aronofsky',
      'Wes Anderson',
      'Coen Brothers',
      'Sofia Coppola',
      'Paul Thomas Anderson',
      'Terrence Malick',
      'Jean-Pierre Jeunet',
      'Alejandro González Iñárritu',
      'Guillermo del Toro',
      'Danny Boyle',
      'Yorgos Lanthimos',
      'Akira Kurosawa',
      'Hayao Miyazaki',
      'Federico Fellini',
      'Michel Gondry',
      'Gaspar Noé',
      'Béla Tarr',
      'Lars von Trier',
      'Jean-Luc Godard',
      'François Truffaut',
      'David Fincher',
      'James Cameron',
      'Oliver Stone',
      'Robert Rodriguez',
      'Michael Bay',
      'Guy Ritchie',
      'Ridley Scott',
      'Tony Scott',
      'John Woo',
      'John Carpenter',
      'Terry Gilliam',
      'Roman Polanski',
      'Sergio Leone',
      'F.W. Murnau',
      'Orson Welles',
      'John Ford',
      'Billy Wilder',
      'Frank Capra',
      'John Huston',
      'Howard Hawks',
      'Stanley Donen',
      'Gene Kelly',
      'Blake Edwards',
      'Robert Altman',
      'Sidney Lumet',
      'Mike Nichols',
      'Woody Allen',
      'Clint Eastwood',
      'Peter Jackson',
      'James Whale',
      'Todd Haynes',
      'Jim Jarmusch',
      'Richard Linklater',
      'Barry Jenkins',
      'Spike Jonze',
      'Park Chan-wook',
      'Sion Sono',
      'Takeshi Kitano',
      'Hirokazu Kore-eda',
      'Abbas Kiarostami',
      'Wim Wenders',
      'Andrei Tarkovsky',
      'Ingmar Bergman',
      'Luchino Visconti',
      'Federico Fellini',
      'Michelangelo Antonioni',
      'Robert Bresson',
      'Jean Cocteau',
      'Marcel Carné',
      'Jacques Tati',
      'Bertrand Tavernier',
      'Jean-Jacques Annaud',
      'Luc Besson',
      'Jean-Pierre Melville',
      'Louis Malle',
      'Claude Chabrol',
      'François Ozon',
      'Patrice Leconte',
      'Leos Carax',
      'Gaspar Noé',
      'Jacques Audiard',
      'Céline Sciamma',
      'Mia Hansen-Løve',
      'Lynne Ramsay',
      'Steve McQueen',
      'Jordan Peele',
      'Taika Waititi',
      'Ryan Coogler',
      'Ava DuVernay',
      'Kathryn Bigelow',
      'Sofia Coppola',
      'Greta Gerwig',
    ],
  },
};
