export const placesChips = [
  {
    id: 'locations',
    name: 'Locations',
    description: 'Exotic and visually stunning locations',
    chips: [
      'Santorini, Greece',
      'Machu Picchu, Peru',
      'The Grand Canyon, Arizona, USA',
      'The Great Barrier Reef, Australia',
      'The Northern Lights, Norway',
      'The Sistine Chapel, Vatican City',
      'The Taj Mahal, India',
      'The Great Wall of China',
      'The Colosseum, Italy',
      'The Pyramids of Giza, Egypt',
      'The Cliffs of Moher, Ireland',
      'The Galapagos Islands, Ecuador',
      'The Acropolis of Athens, Greece',
      'The Amazon Rainforest, Brazil',
      'The Swiss Alps, Switzerland',
      'The Sahara Desert, North Africa',
      'The Venice Canals, Italy',
      'The Victoria Falls, Zambia/Zimbabwe',
      'The Yosemite Valley, California, USA',
      'The Cinque Terre, Italy',
      'The Petra, Jordan',
      'The Blue Lagoon, Iceland',
      'The Plitvice Lakes National Park, Croatia',
      'The Golden Gate Bridge, California, USA',
      'The Neuschwanstein Castle, Germany',
      'The Bali Rice Terraces, Indonesia',
      'The Angkor Wat, Cambodia',
      'The Machir Bay, Scotland',
      'The Ha Long Bay, Vietnam',
      'The Yellowstone National Park, Wyoming, USA',
      'The Wulingyuan Scenic Area, China',
      'The Mount Everest Base Camp, Nepal',
      'The Arashiyama Bamboo Grove, Japan',
      'The Moai Statues, Easter Island',
      'The Bryce Canyon National Park, Utah, USA',
      'The Torres del Paine National Park, Chile',
      'The Alhambra, Spain',
      'The Niagara Falls, Canada/USA',
      'The Rila Monastery, Bulgaria',
      'The Palace of Versailles, France',
      'The Mont Saint Michel, France',
      'The Machuca, Chile',
      'The Sigiriya, Sri Lanka',
      'The Dead Sea, Jordan/Israel/Palestine',
      'The Blue Ridge Mountains, Virginia, USA',
      'The Red Beach, China',
      "The Giant's Causeway, Northern Ireland",
      'The Cappadocia, Turkey',
      'The White Sands National Park, New Mexico, USA',
      'The Bay of Fundy, Canada',
      'The Sagrada Familia, Spain',
      'The Red Square, Russia',
      'The Serengeti National Park, Tanzania',
      'The Haiku Stairs, Hawaii, USA',
      'The Stonehenge, England',
      'The Palace of Westminster, England',
      'The Sagano Bamboo Forest, Japan',
      'The Aletsch Glacier, Switzerland',
      'The Wai-O-Tapu Thermal Wonderland, New Zealand',
      'The Marble Caves, Chile',
      'The Huangshan Mountains, China',
      'The Keukenhof Gardens, Netherlands',
      'The Pamukkale, Turkey',
      'The Grand Tetons National Park, Wyoming, USA',
      'The Mount Kilimanjaro, Tanzania',
      'The Anguilla Beaches, Caribbean',
      'The Blue Hole, Belize',
      'The Namib Desert, Namibia',
      'The Emerald Lake, Canada',
      'The Fjords of Norway',
      'The Hoh Rainforest, Washington, USA',
      'The Rainbow Mountains, China',
      'The Banff National Park, Canada',
      'The Placencia Beach, Belize',
    ],
  },
  {
    id: 'astro',
    name: 'Astronomical',
    description: 'A few places around the universe',
    chips: [
      'Andromeda Galaxy',
      'Milky Way Galaxy',
      'Orion Nebula',
      'Crab Nebula',
      'Pillars of Creation',
      'Sombrero Galaxy',
      'Ant Nebula',
      "Cat's Eye Nebula",
      'Carina Nebula',
      'Black Hole V616 Monocerotis',
      'Cartwheel Galaxy',
      'Whirlpool Galaxy',
      'Sunflower Galaxy',
      'Horsehead Nebula',
      'Eskimo Nebula',
      'Hourglass Nebula',
      'Butterfly Nebula',
      'Ring Nebula',
      'Helix Nebula',
      'Dumbbell Nebula',
      'Spiral Galaxy NGC 1672',
      'Spiral Galaxy NGC 1300',
      'Spiral Galaxy NGC 891',
      'Large Magellanic Cloud',
      'Small Magellanic Cloud',
      'Tadpole Galaxy',
      'Hubble Deep Field',
      'Leo Triplet Galaxy Group',
      'Virgo Cluster',
      'Fornax Cluster',
      'Hickson Compact Group 87',
      'Abell 2218 Galaxy Cluster',
      'Abell 1689 Galaxy Cluster',
      'Bullet Cluster',
      'Sombrero Galaxy',
      'Butterfly Cluster',
      'Jewel Box Cluster',
      'Eta Carinae',
      'Boomerang Nebula',
      'Eta Aquarids Meteor Shower',
      'Alpha Centauri',
      'Betelgeuse',
      'Rigel',
      'Sirius',
      'Proxima Centauri',
      'Kepler-186f',
      'Kepler-62f',
      'Kepler-22b',
      'Gliese 581c',
      'Gliese 667Cc',
      'Trappist-1',
      'The Moon',
      'Mars',
      'Jupiter',
      'Saturn',
      'Uranus',
      'Neptune',
      'Pluto',
      'Europa',
      'Enceladus',
      'Titan',
      'Triton',
      'Charon',
      'Comet 67P/Churyumov-Gerasimenko',
      'Asteroid Belt',
      'Kuiper Belt',
      'Oort Cloud',
      'Interstellar Medium',
      'Dark Matter Halo',
      'Cosmic Microwave Background Radiation',
      'Cosmic Strings',
      'Gamma Ray Bursts',
      'Pulsars',
      'Quasars',
      'Supernovae',
      'White Dwarfs',
      'Black Holes',
      'Neutron Stars',
      'Nebulae',
      'Solar Flares',
      'Coronal Mass Ejections',
      'Aurora Borealis',
      'Aurora Australis',
      'Perseid Meteor Shower',
      'Leonid Meteor Shower',
      'Geminid Meteor Shower',
      'Orionids Meteor Shower',
      'Lyrid Meteor Shower',
      'Ursid Meteor Shower',
      'Draconid Meteor Shower',
      'Quadrantid Meteor Shower',
      'Asteroid Vesta',
      'Asteroid Ceres',
      'Asteroid Eros',
      'Asteroid Itokawa',
      'Asteroid Gaspra',
      'Asteroid Toutatis',
      'Asteroid Bennu',
      'Asteroid Ryugu',
      'Kuiper Belt Object Pluto',
    ],
  },
];
